id: P003196
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W23664
  title: ལྷ་སའི་དགོན་ཐོ་རིན་ཆེན་སྤུངས་རྒྱན
  author: ''
  volumes:
    528910a702bb44c998346e29f8d18945:
      image_group_id: I4204
      title: ''
      volume_number: 1
      total_pages: 361
