id: I0B97BD9E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T09:29:12+00:00'
last_modified: '2022-06-07T18:20:07.864274+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23664
  title: ལྷ་སའི་དགོན་ཐོ་རིན་ཆེན་སྤུངས་རྒྱན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    0F44:
      image_group_id: I4204
      title: ''
      total_pages: 361
      order: 1
      base_file: 0F44.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
